// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnnnf47NJRfCsL6aQcNeKkNUgal52a28',
    appId: '1:334427181956:web:a08c5c11300c2c4d37c3d1',
    messagingSenderId: '334427181956',
    projectId: 'check-it-4b99e',
    authDomain: 'check-it-4b99e.firebaseapp.com',
    storageBucket: 'check-it-4b99e.appspot.com',
    measurementId: 'G-F4CNSNDFN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARiZW50xQ0LnL388HgyAIFpjpl0vo7y1o',
    appId: '1:334427181956:android:28dcb32bf0ee2aeb37c3d1',
    messagingSenderId: '334427181956',
    projectId: 'check-it-4b99e',
    storageBucket: 'check-it-4b99e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNUM4cGEQ_HcBOQtpfhpg6ZTjCX7lDEnw',
    appId: '1:334427181956:ios:e50293a89095904937c3d1',
    messagingSenderId: '334427181956',
    projectId: 'check-it-4b99e',
    storageBucket: 'check-it-4b99e.appspot.com',
    iosClientId: '334427181956-e5n9h9tevnlfhh24c9dnl5e03r9m7tt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
